### ISSUE TITLE
Input field is not marked as not-valid even when X is not shown and "validator required" is not passing.

### ISSUE THREAD

**Issue by mstrione** [Innqube/ng2-iq-datepicker#1]
![image](https://cloud.githubusercontent.com/assets/8575199/21407883/8096fd26-c7b0-11e6-8819-46f706bb8857.png)

**Comment by mstrione** [comment]
Even if you explore the code, there are no "error" classes assigned to input field

**Comment by mstrione** [comment]
Looking at the markup I saw that there is a class "invaliddate" when date is not valid.

**Comment by diegofsza** [comment]
Made some examples myself and validators worked as expected
